// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiknttqmcumuuulnuouz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpa250dHFtY3VtdXV1bG51b3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTgyMTcsImV4cCI6MjA2OTI5NDIxN30.ivtHY1H1gOlN1bNH69CvyAiHKAlwYMDW6OOIf5gIdNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});